
Use SANDBOXES.WILLIBALD_DEV;

SELECT 'DROP TABLE "' || table_schema || '"."' || table_name || '";' AS drop_statement
FROM information_schema.tables
WHERE table_schema = 'WILLIBALD_DEV'
  AND table_catalog = 'SANDBOXES' AND Table_name LIKE 'HUB_%';

  SELECT 'TRUNCATE TABLE "' || table_schema || '"."' || table_name || '";' AS drop_statement
FROM information_schema.tables
WHERE table_schema = 'WILLIBALD_DEV' AND Table_name LIKE 'ROAD_%'
  AND table_catalog = 'SANDBOXES' ;

    SELECT 'TRUNCATE TABLE "' || table_schema || '"."' || table_name || '";' AS drop_statement
FROM information_schema.tables
WHERE table_schema = 'WILLIBALD_DEV' AND Table_name LIKE 'WEB_%'
  AND table_catalog = 'SANDBOXES' ;

-- TRUNCATE TABLE "WILLIBALD_DEV"."ROADSHOW_KUNDE";
-- TRUNCATE TABLE "WILLIBALD_DEV"."ROADSHOW_VEREINSPARTNER";
-- TRUNCATE TABLE "WILLIBALD_DEV"."ROADSHOW_BESTELLUNG";
-- TRUNCATE TABLE "WILLIBALD_DEV"."ROADSHOW_RS_BESTELLUNG";
-- TRUNCATE TABLE "WILLIBALD_DEV"."ROADSHOW_PRODUKT";


-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_POSITION";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_LIEFERUNG";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_KUNDE";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_LIEFERADRESSE";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_KATEGORIE";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_LIEFERDIENST";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_BESTELLUNG";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_PRODUKT";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_VEREINSPARTNER";
-- TRUNCATE TABLE "WILLIBALD_DEV"."WEBSHOP_WOHNORT";

-- Commit;