project1:
  outputs:
    dev:
      account: EUFXFNV-QBEYOND-PARTNER
      database: SANDBOXES
      password: EthanNW@7n775680
      role: QBEYOND_DS_RL
      schema: WILLIBALD_DEV
      threads: 1
      type: snowflake
      user: VPARAB
      warehouse: QBEYOND_DS_WH
  target: dev

