name: 'gcp_dv_project2'
version: '1.0.0'
config-version: 2

profile: 'gcp_dv_project2'

model-paths: ["models"]

models:
  gcp_dv_project2:

    # Staging models
    staging:
      +schema: staging
      +materialized: view

    # Raw Vault models
    raw_vault:
      hub:
        +schema: hub
        +materialized: table

      link:
        +schema: link
        +materialized: table

      sat:
        +schema: sat
        +materialized: table
