gcp_dv_project2:  
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: velvety-glazing-472909-h6
      dataset: staging   
      threads: 4
      # keyfile: C:/Users/Vinayak-SitaramParab/keys/bq_service_account.json
      keyfile: /app/bq_service_account.json
      timeout_seconds: 300
      location: US