FROM apache/beam_python3.8_sdk:2.45.0
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY gcp_to_bigq_pipeline.py /opt/gcp_to_bigq_pipeline.py
ENTRYPOINT ["python", "/opt/gcp_to_bigq_pipeline.py"]
