version: 2

sources:
  - name: roadshow
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: ROADSHOW_BESTELLUNG
      - name: ROADSHOW_KUNDE
      - name: ROADSHOW_RS_BESTELLUNG
      - name: ROADSHOW_VEREINSPARTNER
      - name: ROADSHOW_PRODUKT

  - name: webshop
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: WEBSHOP_KUNDE
      - name: WEBSHOP_BESTELLUNG
      - name: WEBSHOP_WOHNORT
      - name: WEBSHOP_LIEFERADRESSE
      - name: WEBSHOP_VEREINSPARTNER
      - name: WEBSHOP_KATEGORIE
      - name: WEBSHOP_PRODUKT
      - name: WEBSHOP_POSITION
      - name: WEBSHOP_LIEFERUNG
      - name: WEBSHOP_LIEFERDIENST
