version: 2

sources:
  - name: roadshow
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: ROADSHOW_BESTELLUNG
      - name: ROADSHOW_KUNDE

  - name: webshop
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: WEBSHOP_KUNDE
      - name: WEBSHOP_BESTELLUNG
