version: 2

sources:
  - name: webshop
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: Kunde
      - name: Bestellung

  - name: roadshow
    database: SANDBOXES
    schema: "{{ target.schema }}"
    tables:
      - name: Kunde
      - name: Bestellung
